<?xml version="1.0" encoding="utf-8"?><Database Name="examenNET" Class="BDTESTDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=MARCELO;Initial Catalog=examenNET;Integrated Security=True" SettingsObjectName="testAjaxYLINQ.Properties.Settings" SettingsPropertyName="examenNETConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Sexo" Member="Sexos">
    <Type Name="Sexo">
      <Column Name="id_sexo" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre_sexo" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
</Database>